[package]
name = "welcome-msg"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
crossterm = "0.29.0"
figlet-rs = "0.1.5"
serde = { version = "1.0.223", features = ["derive"] }
serde_json = "1.0.145"
